version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
    stdin_open: true
    tty: true
    depends_on:
      - database
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sequelize-api
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
